### PR TITLE
Revert "Add GitHub Community Forum Code of Conduct"

### PR DESCRIPTION
**Pull request by ettaboyle**
Reverts github-community/.github#4

### CODE REVIEW

**Review by miteokaku — COMMENTED** [review]
Help

**Comment by SIXX5GXT** [comment]
Assailant

**Comment by SIXX5GXT** [comment]
- [x] Assailant

**Comment by SIXX5GXT** [comment]
I know you know I am after u

**Comment by surgarshorts** [comment]
I need help please

**Review by support-designfitout — COMMENTED** [review]
Retrieving the files and let GitHub retry to pull the MY_SECRET

**Pull request merged**
