### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AndreaGriffiths11**
This pull request includes a minor update to the `profile/README.md` file. The URL for the "GitHub Events" link has been updated to point to the GitHub Virtual Meetup page on Meetup.com instead of the previous GitHub Events page.

### CODE REVIEW

**Comment by TheMikeyRoss** [comment]
No

**Review by ettaboyle — APPROVED** [review]
🚀

**Review by Csaba1205 — COMMENTED** [review]
Ve

**Review by B4itsG — COMMENTED** [review]
profile/README.md

**Review by B4itsG — COMMENTED** [review]
profile/README.md

**Review by B4itsG — COMMENTED** [review]
profile/README.md

**Comment by Yaktredd** [comment]
> This pull request includes a minor update to the `profile/README.md` file. The URL for the "GitHub Events" link has been updated to point to the GitHub Virtual Meetup page on Meetup.com instead of the previous GitHub Events page.

__

**Comment by bmgparts** [comment]
good

**Review by smuarif0505-creator — COMMENTED** [review]
good organizer

**Review by kbackpeople-jpg — COMMENTED** [review]
``

**Comment by andrecalixtro-a11y** [comment]
Het

**Comment by andrecalixtro-a11y** [comment]
> ``

Hey

**Comment by jay-2611** [comment]
got it

**Comment by andrecalixtro-a11y** [comment]
Hey

**Comment by andrecalixtro-a11y** [comment]
Sent from my iPhone

**Comment by awingfield916-tech** [comment]
Let's get it!

**Pull request merged**
