### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Gatito1010**

### CODE REVIEW

**Comment by Gatito1010** [comment]
> _ No description provided. _

**Comment by brasil8807-pixel** [comment]
> > _ No description provided. _

https://github.com/community/.github/pull/16#issue-1330912736

**Comment by brasil8807-pixel** [comment]
#

**Comment by brasil8807-pixel** [comment]
https://github.com/community/.github/pull/16#issuecomment-1207330619

**Pull request closed without merging**
