### PR TITLE
zoevailanu3@gmail.com

### PR DESCRIPTION
**Pull request by zvailanu98**
https://github.com/super-linter/super-linter/discussions/4871#discussion-5861714

### CODE REVIEW

**Comment by ywad** [comment]
Uploading received_413838991468368.mp4…

**Review by Roddy8720 — COMMENTED** [review]
https://github.com/orgs/community/discussions/127455afbd39f0bde250d06c0c9d12385a50329088f8a5https://github.com/GoogleChrome/lighthouse/issues/16101@otter-computer - [ ] @ettaboyle ~~~~

**Review by Zolitoi — COMMENTED** [review]
1111

**Review by TheGiraffe3 — COMMENTED** [review]
What about this? Is this the way the style is supposed to be?
EDIT: apparently it didn't show the changes I was wondering about. Should line 2 have a space in between the # and the word?

**Comment by Jaimesfm** [comment]
- #- [ ] - @[****[@@]()****]()

**Comment by Jaimesfm** [comment]
@juanpflores 
- [ ] - #@juanpflores [__]()

**Pull request closed without merging**
