### PR TITLE
Add auto-close-pr.yml

### PR DESCRIPTION
**Pull request by otter-computer**
Adds workflow to automatically close PRs to this repository

### CODE REVIEW

**Comment by Dreaangel** [comment]
Yes!!! Finally!!!👍👍🤔🌄🌄

**Review by Doni108doni108 — COMMENTED** [review]
****

**Review by Doni108doni108 — COMMENTED** [review]
****

**Comment by Mhmdalimhmd** [comment]
adb shell sh /storage/emulated/0/Android/data/moe.shizuku.privileged.api/start.sh

**Pull request merged**
